# syntax=docker/dockerfile:1

ARG GO_IMAGE=golang:1.23-bookworm

FROM --platform=$BUILDPLATFORM ${GO_IMAGE} AS builder

ARG ARTIFACT_NAME=quicprobe.tar.gz
ARG TARGETOS
ARG TARGETARCH

WORKDIR /workspace/bench/quicprobe

COPY bench/quicprobe/go.mod bench/quicprobe/go.sum ./
RUN go mod download

COPY bench/quicprobe ./

RUN go test ./...

RUN CGO_ENABLED=0 GOOS=${TARGETOS} GOARCH=${TARGETARCH} \
      go build -trimpath -ldflags="-s -w" -o /tmp/quicprobe . && \
    mkdir -p /tmp/quicprobe-artifact/bin /out && \
    cp /tmp/quicprobe /tmp/quicprobe-artifact/bin/quicprobe && \
    tar -C /tmp/quicprobe-artifact -czf "/out/${ARTIFACT_NAME}" .

FROM scratch AS artifact
COPY --from=builder /out/ /
